name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          config_timezone: Europe/Warsaw
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          base: metadata
          base_indepth: yes
          repositories_forks: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_categories: markup, programming
          config_display: large
          config_octicon: yes
          config_twemoji: yes
